apiVersion: v1
kind: Pod
metadata:
  name: kaiwang-login
spec:
  containers:
  - name: login
    #image: gitlab-registry.nautilus.optiputer.net/wangjinjie722/kaiwang-py2.7
    #    image: gitlab-registry.nautilus.optiputer.net/wangjinjie722/kaiwang-image-ucsd
    image: gitlab-registry.nautilus.optiputer.net/yol070/research-containers/research-login-v2
    command: ["/bin/bash"]
    args: ["-c", "sleep infinity"]
    resources:
      requests:
        memory: "8Gi"
        cpu: 2
      limits:
        nvidia.com/gpu: 1
        memory: "8Gi"
        cpu: 2
    volumeMounts:
    - name: kaiwang-volume     #use your own volune path
      mountPath: /kaiwang-volume
  restartPolicy: Never
  volumes:
    - name: kaiwang-volume
      persistentVolumeClaim:
        claimName: kaiwang-volume
